name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install and build
      run: yarn
    - name: Run Tests
      run: yarn test >> coverage.txt
    - name: Extract coverage percentage
      id: extract_coverage
      run: |
        COVERAGE=$(awk '/Statements/ {print $3}' coverage.txt | tr -d '%')
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        echo "COVERAGE=$COVERAGE"
    - name: Create coverage badge
      run: |
        # Ensure the COVERAGE environment variable is properly formatted
        COVERAGE="${{ env.COVERAGE }}"

        # Create the JSON payload
        echo "{\"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"$COVERAGE%\", \"color\": \"brightgreen\"}" > badge.json

        # Use curl to post the JSON to Shields.io
        curl -X POST -H "Content-Type: application/json" \
          -d @badge.json \
          https://img.shields.io/endpoint \
          -o coverage-badge.json
    - name: Configure Git for pushing
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    - name: Commit coverage badge
      run: |
        mv coverage-badge.json ./coverage.json
        git add .
        git commit -m "Update coverage badge"
        git push origin master
    - name: Push changes
      run: |
        git push origin HEAD:master